# Generated by Django 5.2.15 on 2026-06-18 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officepolicy',
            name='office_end',
            field=models.TimeField(default=datetime.time(18, 30)),
        ),
        migrations.AlterField(
            model_name='officepolicy',
            name='office_start',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
    ]
